#!/usr/bin/env python3
"""
Cloud Run Job: Fetch economic events and write to Cloud SQL.

Replaces the GitHub Actions workflow update_economic_events_calendar.yml
(the Cloud SQL write portion -- the workflow also runs analysis scripts).

Sources:
  1. Existing market_events.json (generated by scripts/market_events_tracker.py)
  2. FRED API releases calendar (upcoming high-impact releases)

Scheduled by Cloud Scheduler daily at 7:00 AM ET weekdays.

Usage:
    python -m gcp.fetchers.fetch_economic_events [--source json|fred|all]
"""

import argparse
import json
import logging
import os
import sys
from datetime import datetime, date, timedelta, time as dt_time
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from gcp.database import upsert_dataframe, is_cloud_sql_configured
from lib.logging_config import setup_logging

logger = logging.getLogger(__name__)

# Known high-impact US economic events and their typical release times (ET).
# This mirrors the calendar maintained in scripts/market_events_tracker.py
# but in a format ready for Cloud SQL.
EVENT_IMPORTANCE = {
    'CPI': 'high',
    'Core CPI': 'high',
    'FOMC': 'high',
    'FOMC Minutes': 'medium',
    'NFP': 'high',
    'Non-Farm Payrolls': 'high',
    'GDP': 'high',
    'GDP Advance': 'high',
    'GDP Second': 'medium',
    'GDP Final': 'medium',
    'PCE': 'high',
    'Core PCE': 'high',
    'PPI': 'medium',
    'Retail Sales': 'medium',
    'ISM Manufacturing PMI': 'medium',
    'ISM Services PMI': 'medium',
    'Housing Starts': 'low',
    'Initial Jobless Claims': 'low',
    'Durable Goods Orders': 'medium',
    'Consumer Confidence': 'medium',
    'Michigan Consumer Sentiment': 'medium',
    'Industrial Production': 'low',
    'Existing Home Sales': 'low',
    'New Home Sales': 'low',
    'Trade Balance': 'low',
    'Treasury Auction': 'low',
}


def load_events_from_json(json_path: str = None) -> pd.DataFrame:
    """Load economic events from the existing market_events.json file.

    Returns a DataFrame with columns matching the economic_events schema.
    """
    if json_path is None:
        json_path = os.environ.get(
            'EVENTS_JSON_PATH', 'data/economic_events/market_events.json'
        )

    path = Path(json_path)
    if not path.exists():
        logger.warning("Events JSON not found: %s", path)
        return pd.DataFrame()

    with open(path) as f:
        raw = json.load(f)

    rows = []
    events = raw if isinstance(raw, list) else raw.get('events', raw.get('data', []))

    for ev in events:
        event_date = ev.get('date') or ev.get('event_date')
        if not event_date:
            continue

        event_name = ev.get('event_type') or ev.get('event_name') or ev.get('name', '')
        if not event_name:
            continue

        # Parse the release time if available
        event_time = None
        raw_time = ev.get('time') or ev.get('event_time') or ev.get('typical_release_time', '')
        if raw_time:
            try:
                # Handle formats like "08:30 ET", "14:00", etc.
                clean = raw_time.replace(' ET', '').replace(' EST', '').replace(' EDT', '').strip()
                if ':' in clean:
                    parts = clean.split(':')
                    event_time = dt_time(int(parts[0]), int(parts[1]))
            except (ValueError, IndexError):
                pass

        importance = ev.get('importance') or ev.get('expected_impact', '')
        # Normalize importance to low/medium/high
        importance = importance.lower() if importance else ''
        if importance in ('very high',):
            importance = 'high'
        elif importance in ('low-medium',):
            importance = 'medium'
        elif importance not in ('low', 'medium', 'high'):
            importance = EVENT_IMPORTANCE.get(event_name, 'medium')

        rows.append({
            'event_date': pd.to_datetime(event_date).date(),
            'event_time': event_time,
            'event_name': event_name[:200],
            'country': ev.get('country', 'US')[:10],
            'importance': importance,
            'actual': str(ev.get('actual', ''))[:50] or None,
            'forecast': str(ev.get('consensus', ev.get('forecast', '')))[:50] or None,
            'previous': str(ev.get('previous', ''))[:50] or None,
        })

    if not rows:
        return pd.DataFrame()

    df = pd.DataFrame(rows)
    # Deduplicate on the unique constraint columns
    df = df.drop_duplicates(subset=['event_date', 'event_name'], keep='last')
    logger.info("Loaded %d events from JSON", len(df))
    return df


def fetch_fred_releases(days_ahead: int = 30) -> pd.DataFrame:
    """Fetch upcoming FRED release dates via the FRED releases API.

    Requires FRED_API_KEY environment variable.
    Returns a DataFrame matching the economic_events schema.
    """
    api_key = os.environ.get('FRED_API_KEY')
    if not api_key:
        logger.info("FRED_API_KEY not set -- skipping FRED releases")
        return pd.DataFrame()

    try:
        import requests as req
    except ImportError:
        logger.warning("requests not available")
        return pd.DataFrame()

    today = date.today()
    end = today + timedelta(days=days_ahead)

    # Use FRED releases/dates endpoint for upcoming releases
    url = 'https://api.stlouisfed.org/fred/releases/dates'
    params = {
        'api_key': api_key,
        'file_type': 'json',
        'realtime_start': today.isoformat(),
        'realtime_end': end.isoformat(),
        'include_release_dates_with_no_data': 'false',
    }

    try:
        resp = req.get(url, params=params, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        logger.warning("FRED releases/dates request failed: %s", e)
        return pd.DataFrame()

    releases = data.get('release_dates', [])
    if not releases:
        return pd.DataFrame()

    rows = []
    for rel in releases:
        name = rel.get('release_name', '')
        if not name:
            continue
        rows.append({
            'event_date': pd.to_datetime(rel['date']).date(),
            'event_time': None,
            'event_name': name[:200],
            'country': 'US',
            'importance': EVENT_IMPORTANCE.get(name, 'low'),
            'actual': None,
            'forecast': None,
            'previous': None,
        })

    df = pd.DataFrame(rows)
    df = df.drop_duplicates(subset=['event_date', 'event_name'], keep='last')
    logger.info("Fetched %d upcoming FRED releases", len(df))
    return df


def persist_to_cloud_sql(df: pd.DataFrame) -> int:
    """Write events DataFrame to the economic_events Cloud SQL table."""
    if df.empty:
        logger.info("No events to persist")
        return 0

    if not is_cloud_sql_configured():
        logger.warning("Cloud SQL not configured -- skipping persist")
        return 0

    n = upsert_dataframe(df, 'economic_events', ['event_date', 'event_name'])
    logger.info("Upserted %d rows to economic_events", n)
    return n


def main():
    setup_logging()
    parser = argparse.ArgumentParser(description='Fetch economic events → Cloud SQL')
    parser.add_argument(
        '--source', choices=['json', 'fred', 'all'], default='all',
        help='Data source: json (local file), fred (API), or all (default)',
    )
    parser.add_argument(
        '--json-path', type=str, default=None,
        help='Path to market_events.json (default: data/economic_events/market_events.json)',
    )
    parser.add_argument(
        '--days-ahead', type=int, default=30,
        help='Days ahead to fetch FRED releases (default: 30)',
    )
    args = parser.parse_args()

    frames = []

    if args.source in ('json', 'all'):
        df_json = load_events_from_json(args.json_path)
        if not df_json.empty:
            frames.append(df_json)

    if args.source in ('fred', 'all'):
        df_fred = fetch_fred_releases(args.days_ahead)
        if not df_fred.empty:
            frames.append(df_fred)

    if not frames:
        logger.warning("No events loaded from any source")
        return

    combined = pd.concat(frames, ignore_index=True)
    combined = combined.drop_duplicates(subset=['event_date', 'event_name'], keep='last')
    logger.info("Total events to persist: %d", len(combined))

    n = persist_to_cloud_sql(combined)
    print(f"Persisted {n} economic events to Cloud SQL")


if __name__ == '__main__':
    main()
