#!/usr/bin/env bash
# Refresh the Superpowers skills vendored in .claude/skills/ to an upstream
# release tag of https://github.com/obra/superpowers.
#
#   update_superpowers.sh           # newest release tag
#   update_superpowers.sh v6.4.2    # a specific tag (also allows a downgrade)
#
# Cloud sessions do not install plugins from enabledPlugins, and multi-repo
# sessions skip repo SessionStart hooks, so the skills are committed instead.
# This script is how that copy stays current; the weekly
# update-superpowers.yml workflow runs it and opens a PR with the result.
#
# Output contract (the workflow relies on it):
#   stdout  upstream release notes for every version after the vendored one,
#           empty when already up to date
#   stderr  progress
#   exit 0  updated, or already up to date; nonzero on any failure
#
# The skills named in SUPERPOWERS.md are the only folders this script removes
# or overwrites. A repo's own skill that collides with an upstream name fails
# the run rather than being replaced.
set -euo pipefail

UPSTREAM=https://github.com/obra/superpowers
ROOT=$(git rev-parse --show-toplevel)
DEST="$ROOT/.claude/skills"
NOTE="$DEST/SUPERPOWERS.md"
SELF=${0#"$ROOT"/}

log() { echo "update-superpowers: $*" >&2; }
die() { log "ERROR: $*"; exit 1; }
# Final release tags only (vMAJOR.MINOR.PATCH), oldest first. Prereleases are
# excluded: GNU sort -V orders v6.5.0-rc.1 after v6.5.0, so keeping them would
# vendor a release candidate over the final release.
release_tags() {
  git ls-remote --tags --refs "$UPSTREAM" 'v*' | sed 's#.*refs/tags/##' \
    | grep -E '^v[0-9]+(\.[0-9]+)*$' | sort -V
}
newest_of() { printf '%s\n%s\n' "$1" "$2" | sort -V | tail -n 1; }

current=$(sed -n 's/^- Version: //p' "$NOTE")
[ -n "$current" ] || die "no '- Version:' line in $NOTE"

if [ -n "${1:-}" ]; then
  target=$1
  # git clone --branch also accepts a branch name, which would vendor
  # unreleased upstream code recorded as "Version: main".
  release_tags | grep -qx -- "$target" \
    || die "$target is not a release tag at $UPSTREAM"
else
  target=$(release_tags | tail -n 1)
  [ -n "$target" ] || die "no release tags found at $UPSTREAM"
  [ "$(newest_of "$current" "$target")" = "$target" ] \
    || die "vendored $current is newer than upstream's newest tag $target"
fi

if [ "$target" = "$current" ]; then
  log "already at $current"
  exit 0
fi
log "updating $current -> $target"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
git -c advice.detachedHead=false clone -q --depth 1 --branch "$target" \
  "$UPSTREAM" "$tmp/sp"
src="$tmp/sp"
[ -f "$src/skills/using-superpowers/SKILL.md" ] \
  || die "$target has no skills/using-superpowers/SKILL.md; upstream layout changed"
commit=$(git -C "$src" rev-parse HEAD)

old_skills=$(sed -n '/^<!-- skills:start -->$/,/^<!-- skills:end -->$/s/^- //p' "$NOTE")
[ -n "$old_skills" ] || die "no skill list between the skills markers in $NOTE"
new_skills=$(for d in "$src"/skills/*/; do basename "$d"; done | sort)

for name in $new_skills; do
  [[ $name =~ ^[a-z0-9-]+$ ]] || die "unexpected upstream skill name: $name"
  if [ -e "$DEST/$name" ] && ! grep -qx "$name" <<<"$old_skills"; then
    die "upstream skill '$name' collides with this repo's own .claude/skills/$name"
  fi
done

for name in $old_skills; do
  [[ $name =~ ^[a-z0-9-]+$ ]] || die "unexpected vendored skill name: $name"
  rm -rf "${DEST:?}/$name"
done
for name in $new_skills; do
  cp -a "$src/skills/$name" "$DEST/$name"
done
cp "$src/LICENSE" "$DEST/SUPERPOWERS-LICENSE"

{
  cat <<EOF
# Vendored Superpowers skills

Generated by \`$SELF\`; do not edit by hand.
The skill folders listed below are copied unmodified from
$UPSTREAM, MIT licensed (see SUPERPOWERS-LICENSE).

- Version: $target
- Commit: $commit

<!-- skills:start -->
EOF
  # shellcheck disable=SC2086  # names were validated as [a-z0-9-]+ above
  printf -- '- %s\n' $new_skills
  cat <<EOF
<!-- skills:end -->

## Why vendored

Cloud sessions on claude.ai/code do not install plugins listed under
\`enabledPlugins\` / \`extraKnownMarketplaces\`, and multi-repo sessions skip
repo SessionStart hooks. Skills committed under \`.claude/skills/\` load from
the clone in every session, so this copy is the reliable path.

## Differences from the plugin install

- Skills load unnamespaced: the text refers to \`superpowers:brainstorming\`,
  the skill here is \`brainstorming\`. Same for every \`superpowers:<name>\`.
- The plugin's SessionStart hook, which preloads \`using-superpowers\` into
  context, is not included. Skills still trigger from their descriptions.

## Updating

\`.github/workflows/update-superpowers.yml\` checks for a new release tag
every Monday and opens a PR when there is one. To update by hand, run
\`$SELF\` (optionally with a tag) and commit the result.
EOF
} >"$NOTE"

# Release notes for the released versions in (current, target]. Selecting the
# sections by version, rather than reading down to the vendored version's
# heading, keeps a downgrade bounded: an older release's notes have no heading
# for the newer vendored version, so that scan ran to the end of the file.
if [ "$(newest_of "$current" "$target")" != "$target" ]; then
  echo "Downgrade from $current to $target: no forward release notes apply."
else
  in_range=" "
  for tag in $(release_tags); do
    if [ "$tag" != "$current" ] && [ "$(newest_of "$current" "$tag")" = "$tag" ] \
      && [ "$(newest_of "$tag" "$target")" = "$target" ]; then
      in_range+="$tag "
    fi
  done
  awk -v set="$in_range" '
    /^## / { split($0, h, " "); on = index(set, " " h[2] " ") > 0 }
    on { print }
  ' "$src/RELEASE-NOTES.md"
fi

log "updated to $target ($commit)"
