#!/usr/bin/env python3
"""
Generate BACKTEST_RESULTS.md from existing backtest CSVs.

Reads the most recent trade-level and timeframe-sweep CSVs per ticker,
runs the analysis, and writes a comprehensive Markdown report with
both raw data tables and narrative insights.

Usage:
    python scripts/generate_backtest_report.py
    python scripts/generate_backtest_report.py --tickers IWM SPY
    python scripts/generate_backtest_report.py --output MY_REPORT.md
"""

import argparse
import sys
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent.parent))

import pandas as pd
import numpy as np

from lib.config import load_config
from lib.insights import (
    _exit_stats,
    _direction_stats,
    insight_trade_profile,
    insight_exit_reason_table,
    insight_direction_table,
    insight_narrative_exit_reasons,
    insight_narrative_winners_losers,
    insight_timeframe_sweep,
    insight_combo_sweep,
    insight_what_numbers_mean,
)


RESULTS_DIR = Path(__file__).resolve().parent.parent / "data" / "backtest_results"
DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "BACKTEST_RESULTS.md"
TICKERS = ["IWM", "SPY", "QQQ"]


# ---------------------------------------------------------------------------
# CSV discovery
# ---------------------------------------------------------------------------

def find_latest(pattern: str) -> Path | None:
    """Most-recently-modified file matching glob pattern in RESULTS_DIR."""
    files = sorted(RESULTS_DIR.glob(pattern), key=lambda f: f.stat().st_mtime, reverse=True)
    return files[0] if files else None


def find_trade_csv(ticker: str, strat: bool = True) -> Path | None:
    """Find the latest backtest_{ticker}_*.csv with/without strat columns."""
    files = sorted(RESULTS_DIR.glob(f"backtest_{ticker}_*.csv"),
                   key=lambda f: f.stat().st_mtime, reverse=True)
    for f in files:
        try:
            df = pd.read_csv(f, nrows=2)
        except Exception:
            continue
        has_strat = 'ftfc_score' in df.columns and df['ftfc_score'].notna().any()
        # For strat: want a file where strat_bonus can be nonzero
        if strat and has_strat:
            return f
        if not strat:
            return f
    return files[0] if files else None


def find_sweep_csv(ticker: str) -> Path | None:
    return find_latest(f"timeframe_sweep_{ticker}_*.csv")


def load_trades(filepath: Path) -> pd.DataFrame:
    df = pd.read_csv(filepath, parse_dates=["entry_time", "exit_time"])
    df["duration_min"] = (df["exit_time"] - df["entry_time"]).dt.total_seconds() / 60.0
    df["won"] = df["return_pct"] > 0
    df["return_bps"] = df["return_pct"] * 10_000
    return df


# ---------------------------------------------------------------------------
# Report assembly
# ---------------------------------------------------------------------------

def build_report(tickers: list[str]) -> str:
    """Assemble the full Markdown report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines: list[str] = []

    lines.append("# Backtest Results & Trade Insights")
    lines.append("")
    lines.append(f"*Auto-generated by `generate_backtest_report.py` — {now}*")
    lines.append("")

    # ----- Strategy parameters -----
    lines += _section_strategy_params(tickers)

    # ----- Load trade data -----
    trade_dfs: dict[str, pd.DataFrame] = {}
    for ticker in tickers:
        fpath = find_trade_csv(ticker, strat=True)
        if fpath is None:
            fpath = find_trade_csv(ticker, strat=False)
        if fpath is None:
            print(f"  [WARN] No backtest CSV for {ticker}")
            continue
        print(f"  {ticker}: {fpath.name}")
        trade_dfs[ticker] = load_trades(fpath)

    if not trade_dfs:
        lines.append("*No backtest data found.*\n")
        return "\n".join(lines)

    # ----- Core backtest results table -----
    lines += _section_core_results(trade_dfs)

    # ----- Trade Duration & Mechanics -----
    lines += _section_duration(trade_dfs)

    # ----- Timeframe sweep -----
    sweep_dfs: dict[str, pd.DataFrame] = {}
    for ticker in tickers:
        fpath = find_sweep_csv(ticker)
        if fpath:
            sweep_dfs[ticker] = pd.read_csv(fpath)
    if sweep_dfs:
        lines += _section_sweep(sweep_dfs)

    # ----- How to read -----
    lines += insight_what_numbers_mean()

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Report sections
# ---------------------------------------------------------------------------

def _section_strategy_params(tickers: list[str]) -> list[str]:
    lines = [
        "## Strategy Parameters",
        "",
        "All entries on **1-minute candles** using a 3-of-5 condition scoring system. "
        "Higher timeframes (5m, 15m, 30m) are used only as **directional filters**, "
        "not as entry timeframes.",
        "",
        "| Parameter | CALL | PUT |",
        "|-----------|------|-----|",
        "| Entry timeframe | 1-minute candles | 1-minute candles |",
        "| Signal conditions | 3 of 5 required | 3 of 5 required |",
        "| Entry window | 9:30–10:00 AM | 9:30–2:00 PM |",
        "",
    ]

    # Per-ticker params
    param_rows: dict[str, dict] = {}
    for ticker in tickers:
        cfg = load_config(ticker=ticker)
        param_rows[ticker] = {
            'call_target': f"+{cfg.exit.call_target:.2%}",
            'put_target': f"+{cfg.exit.put_target:.2%}",
            'call_stop': f"-{cfg.exit.call_stop:.2%}",
            'put_stop': f"-{cfg.exit.put_stop:.2%}",
            'call_time': f"{cfg.exit.call_time_stop} min",
            'put_time': f"{cfg.exit.put_time_stop} min",
        }

    if param_rows:
        tk = list(param_rows.keys())
        lines.append("| Parameter | " + " | ".join(f"**{t}**" for t in tk) + " |")
        lines.append("|-----------|" + "|".join("---" for _ in tk) + "|")
        for label, key in [
            ("Profit target (CALL)", "call_target"),
            ("Profit target (PUT)", "put_target"),
            ("Stop loss (CALL)", "call_stop"),
            ("Stop loss (PUT)", "put_stop"),
            ("Time stop (CALL)", "call_time"),
            ("Time stop (PUT)", "put_time"),
        ]:
            vals = [param_rows.get(t, {}).get(key, "—") for t in tk]
            lines.append(f"| {label} | " + " | ".join(vals) + " |")
        lines.append("")

    return lines


def _section_core_results(trade_dfs: dict[str, pd.DataFrame]) -> list[str]:
    lines = [
        "## Core Backtest Results",
        "",
        "| Ticker | Trades | Win Rate | Avg Win | Avg Loss | PF | Expectancy | Sharpe |",
        "|--------|--------|----------|---------|----------|------|------------|--------|",
    ]
    for ticker, df in trade_dfs.items():
        n = len(df)
        wins = df[df['won']]
        losses = df[~df['won']]
        wr = wins.shape[0] / n if n else 0
        avg_w = wins['return_pct'].mean() if len(wins) else 0
        avg_l = losses['return_pct'].mean() if len(losses) else 0
        pf_num = wins['return_pct'].sum()
        pf_den = abs(losses['return_pct'].sum())
        pf = pf_num / pf_den if pf_den > 0 else 0
        exp = df['return_pct'].mean()
        # Daily Sharpe approximation
        df_day = df.copy()
        df_day['date'] = pd.to_datetime(df_day['entry_time']).dt.date
        daily_pnl = df_day.groupby('date')['return_pct'].sum()
        sharpe = (daily_pnl.mean() / daily_pnl.std() * np.sqrt(252)) if daily_pnl.std() > 0 else 0

        lines.append(
            f"| **{ticker}** "
            f"| {n:,} "
            f"| {wr:.1%} "
            f"| +{avg_w:.2%} "
            f"| {avg_l:.2%} "
            f"| {pf:.2f} "
            f"| {exp:+.3%} "
            f"| {sharpe:.2f} |"
        )
    lines.append("")
    return lines


def _section_duration(trade_dfs: dict[str, pd.DataFrame]) -> list[str]:
    lines = [
        "## Trade Duration & Mechanics",
        "",
        "*How long are you actually in each trade? What exits are you hitting?*",
        "",
    ]

    # Compute stats per ticker
    all_exit: dict[str, dict] = {}
    all_dir: dict[str, dict] = {}
    ticker_profiles: dict[str, dict] = {}

    for ticker, df in trade_dfs.items():
        es = _exit_stats(df)
        ds = _direction_stats(df)
        all_exit[ticker] = es
        all_dir[ticker] = ds

        n = len(df)
        wins = df[df['won']]
        losses = df[~df['won']]
        ticker_profiles[ticker] = {
            'trades': n,
            'wr': wins.shape[0] / n if n else 0,
            'avg_dur': df['duration_min'].mean(),
            'med_dur': df['duration_min'].median(),
            'avg_dur_w': wins['duration_min'].mean() if len(wins) else 0,
            'avg_dur_l': losses['duration_min'].mean() if len(losses) else 0,
            'target_pct': (df['exit_reason'] == 'target').sum() / n if n else 0,
            'stop_pct': (df['exit_reason'] == 'stop_loss').sum() / n if n else 0,
            'time_pct': (df['exit_reason'] == 'time_stop').sum() / n if n else 0,
        }

    # 1. Profile table
    lines += insight_trade_profile(ticker_profiles)

    # 2. Duration by exit reason tables
    lines.append("### Duration by Exit Reason")
    lines.append("")
    for ticker in trade_dfs:
        if ticker in all_exit:
            lines += insight_exit_reason_table(ticker, all_exit[ticker])

    # 3. Narrative insights (the template-driven part)
    lines += insight_narrative_exit_reasons(all_exit)

    # 4. Winners vs Losers insight
    lines += insight_narrative_winners_losers(ticker_profiles)

    # 5. Direction table
    lines += insight_direction_table(all_dir)

    return lines


def _section_sweep(sweep_dfs: dict[str, pd.DataFrame]) -> list[str]:
    lines = [
        "## Timeframe Analysis",
        "",
    ]
    lines += insight_timeframe_sweep(sweep_dfs)
    lines += insight_combo_sweep(sweep_dfs)
    return lines


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description='Generate BACKTEST_RESULTS.md')
    parser.add_argument('--tickers', nargs='+', default=TICKERS)
    parser.add_argument('--output', type=str, default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    print(f"Generating report for {args.tickers}...")
    report = build_report(args.tickers)

    output_path = Path(args.output)
    output_path.write_text(report)
    print(f"Report written to {output_path}")
    print(f"  ({len(report.splitlines())} lines)")


if __name__ == '__main__':
    main()
