"""
AI Insights router — structured multi-agent report endpoints.

Replaces the old Gemini chat endpoint. The report is generated by
the agent pipeline in lib.agents.orchestrator and persisted to
Cloud SQL's insight_reports table. The refresh endpoint enqueues a
run; clients poll /runs/{run_id} until status='done'.

In production, refresh dispatches a Cloud Tasks message to the
Cloud Run job (gcp/insight_pipeline_job.py). In local dev, it falls
back to FastAPI BackgroundTasks so you can exercise the full path
without spinning up infrastructure.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
from uuid import UUID, uuid4

from typing import AsyncGenerator

from fastapi import APIRouter, BackgroundTasks, HTTPException, Path as PathParam
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from lib.agents.model_routing import connect, load_routes_snapshot  # noqa: E402
from lib.agents.orchestrator import run_insight_pipeline  # noqa: E402
from lib.agents.schema import InsightReport  # noqa: E402
import lib.agents.vertex_adapter  # noqa: F401, E402 — registers adapter

router = APIRouter()
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------


class RunStatus(BaseModel):
    id: str
    ticker: str
    status: str
    trigger: str
    started_at: Optional[str] = None
    finished_at: Optional[str] = None
    error: Optional[str] = None
    report_id: Optional[str] = None


class RefreshResponse(BaseModel):
    run_id: str
    ticker: str
    status: str = "queued"


class ReportEnvelope(BaseModel):
    """Payload for GET /api/insights/report/{ticker}."""

    ticker: str
    as_of: str
    report: dict
    model_versions: dict
    cost_usd: Optional[float] = None
    latency_ms: Optional[int] = None


# ---------------------------------------------------------------------------
# DB helpers (raw SQL via the existing model_routing connection)
# ---------------------------------------------------------------------------


def _fetch_latest_report(ticker: str) -> Optional[dict]:
    conn = connect()
    try:
        cur = conn.cursor()
        cur.execute(
            """
            SELECT id::text, ticker, as_of, report, model_versions,
                   cost_usd, latency_ms
            FROM insight_reports
            WHERE ticker = %s
            ORDER BY as_of DESC
            LIMIT 1
            """,
            (ticker.upper(),),
        )
        row = cur.fetchone()
    finally:
        conn.close()
    return _row_to_envelope(row)


def _fetch_report_by_id(report_id: str) -> Optional[dict]:
    conn = connect()
    try:
        cur = conn.cursor()
        cur.execute(
            """
            SELECT id::text, ticker, as_of, report, model_versions,
                   cost_usd, latency_ms
            FROM insight_reports
            WHERE id = %s
            """,
            (report_id,),
        )
        row = cur.fetchone()
    finally:
        conn.close()
    return _row_to_envelope(row)


def _row_to_envelope(row) -> Optional[dict]:
    if not row:
        return None
    return {
        "id": row[0],
        "ticker": row[1],
        "as_of": row[2].isoformat() if row[2] else None,
        "report": row[3],
        "model_versions": row[4],
        "cost_usd": float(row[5]) if row[5] is not None else None,
        "latency_ms": row[6],
    }


def _fetch_report_history(ticker: str, limit: int) -> list[dict]:
    conn = connect()
    try:
        cur = conn.cursor()
        cur.execute(
            """
            SELECT id::text, as_of,
                   report->>'direction' AS direction,
                   report->>'conviction' AS conviction,
                   report->>'thesis' AS thesis,
                   cost_usd
            FROM insight_reports
            WHERE ticker = %s
            ORDER BY as_of DESC
            LIMIT %s
            """,
            (ticker.upper(), limit),
        )
        rows = cur.fetchall()
    finally:
        conn.close()
    return [
        {
            "id": r[0],
            "as_of": r[1].isoformat() if r[1] else None,
            "direction": r[2],
            "conviction": r[3],
            "thesis": r[4],
            "cost_usd": float(r[5]) if r[5] is not None else None,
        }
        for r in rows
    ]


def _insert_run(ticker: str, trigger: str) -> str:
    conn = connect()
    run_id = str(uuid4())
    try:
        cur = conn.cursor()
        cur.execute(
            """
            INSERT INTO insight_runs (id, ticker, status, trigger)
            VALUES (%s, %s, 'queued', %s)
            """,
            (run_id, ticker.upper(), trigger),
        )
        conn.commit()
    finally:
        conn.close()
    return run_id


def _fetch_run(run_id: str) -> Optional[dict]:
    conn = connect()
    try:
        cur = conn.cursor()
        cur.execute(
            """
            SELECT id::text, ticker, status, trigger, started_at,
                   finished_at, error, report_id::text
            FROM insight_runs
            WHERE id = %s
            """,
            (run_id,),
        )
        row = cur.fetchone()
    finally:
        conn.close()
    if not row:
        return None
    return {
        "id": row[0],
        "ticker": row[1],
        "status": row[2],
        "trigger": row[3],
        "started_at": row[4].isoformat() if row[4] else None,
        "finished_at": row[5].isoformat() if row[5] else None,
        "error": row[6],
        "report_id": row[7],
    }


def _update_run_status(
    run_id: str,
    status: str,
    *,
    error: Optional[str] = None,
    report_id: Optional[str] = None,
) -> None:
    conn = connect()
    try:
        cur = conn.cursor()
        if status == "running":
            cur.execute(
                "UPDATE insight_runs SET status='running', started_at=NOW() WHERE id=%s",
                (run_id,),
            )
        elif status == "done":
            cur.execute(
                """
                UPDATE insight_runs
                SET status='done', finished_at=NOW(), report_id=%s
                WHERE id=%s
                """,
                (report_id, run_id),
            )
        elif status == "failed":
            cur.execute(
                """
                UPDATE insight_runs
                SET status='failed', finished_at=NOW(), error=%s
                WHERE id=%s
                """,
                (error, run_id),
            )
        conn.commit()
    finally:
        conn.close()


def _upsert_report(report: InsightReport) -> str:
    """Upsert the report and return its row id."""
    conn = connect()
    row_id = str(uuid4())
    try:
        cur = conn.cursor()
        cur.execute(
            """
            INSERT INTO insight_reports
                (id, ticker, as_of, report, model_versions, cost_usd, latency_ms)
            VALUES (%s, %s, %s, %s::jsonb, %s::jsonb, %s, %s)
            ON CONFLICT (ticker, as_of) DO UPDATE
            SET report = EXCLUDED.report,
                model_versions = EXCLUDED.model_versions,
                cost_usd = EXCLUDED.cost_usd,
                latency_ms = EXCLUDED.latency_ms
            RETURNING id::text
            """,
            (
                row_id,
                report.ticker,
                report.as_of,
                report.model_dump_json(),
                json.dumps(report.model_versions),
                report.run_cost_usd,
                report.run_latency_ms,
            ),
        )
        returned = cur.fetchone()
        if returned:
            row_id = returned[0]
        conn.commit()
    finally:
        conn.close()
    return row_id


# ---------------------------------------------------------------------------
# Background pipeline execution (local-dev only)
# ---------------------------------------------------------------------------


async def _execute_pipeline(run_id: str, ticker: str) -> None:
    """Run the pipeline and persist the result + run-status transitions."""
    _update_run_status(run_id, "running")
    try:
        snapshot = load_routes_snapshot()
        report = await run_insight_pipeline(ticker, snapshot=snapshot)
        report_id = _upsert_report(report)
        _update_run_status(run_id, "done", report_id=report_id)
    except Exception as exc:
        logger.exception("pipeline run %s failed", run_id)
        _update_run_status(run_id, "failed", error=str(exc))


def _is_local_dev() -> bool:
    return os.environ.get("ENV", "local").lower() in ("local", "dev", "development")


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.get("/api/insights/report/{ticker}", response_model=ReportEnvelope)
async def get_insight_report(ticker: str):
    """Return the most recent InsightReport for the ticker."""
    row = _fetch_latest_report(ticker)
    if row is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"No insight report for {ticker.upper()}. "
                "Call POST /api/insights/report/{ticker}/refresh to generate one."
            ),
        )
    return ReportEnvelope(
        ticker=row["ticker"],
        as_of=row["as_of"],
        report=row["report"],
        model_versions=row["model_versions"],
        cost_usd=row["cost_usd"],
        latency_ms=row["latency_ms"],
    )


@router.get("/api/insights/report/{ticker}/history")
async def get_insight_history(ticker: str, limit: int = 20):
    """Return a scannable list of recent reports for the ticker."""
    if limit < 1 or limit > 100:
        raise HTTPException(status_code=400, detail="limit must be between 1 and 100")
    rows = _fetch_report_history(ticker, limit)
    return {"ticker": ticker.upper(), "count": len(rows), "reports": rows}


@router.get("/api/insights/reports/{report_id}", response_model=ReportEnvelope)
async def get_insight_report_by_id(report_id: str):
    """Return a single insight report by row id.

    Used by the frontend History tab to open a past report in the
    full card view. Accepts any id string; invalid UUIDs return 404
    from the database query rather than 400, since operator-facing
    404 is a clearer signal than request-validation 400.
    """
    try:
        UUID(report_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="report_id must be a UUID")
    row = _fetch_report_by_id(report_id)
    if row is None:
        raise HTTPException(status_code=404, detail=f"report {report_id} not found")
    return ReportEnvelope(
        ticker=row["ticker"],
        as_of=row["as_of"],
        report=row["report"],
        model_versions=row["model_versions"],
        cost_usd=row["cost_usd"],
        latency_ms=row["latency_ms"],
    )


@router.post(
    "/api/insights/report/{ticker}/refresh",
    response_model=RefreshResponse,
)
async def refresh_insight_report(
    ticker: str,
    background_tasks: BackgroundTasks,
):
    """Enqueue a fresh pipeline run for the ticker.

    Local dev: runs via FastAPI BackgroundTasks. Durable within the
    process but not across restarts — acceptable for dev only.

    Production: enqueues a Cloud Tasks message to the
    `insight-pipeline-queue`. The task targets the
    `insight-pipeline` Cloud Run job with env overrides
    `INSIGHT_RUN_ID` and `INSIGHT_TICKER`. Cloud Run scale-to-zero
    can't drop the run because the job is invoked fresh. If
    google-cloud-tasks isn't importable we fall back to
    BackgroundTasks with a logged warning so the endpoint remains
    functional.
    """
    ticker_up = ticker.upper()
    trigger = "local_dev" if _is_local_dev() else "on_demand"
    run_id = _insert_run(ticker_up, trigger=trigger)

    if _is_local_dev():
        background_tasks.add_task(_sync_run, run_id, ticker_up)
    else:
        enqueued = _enqueue_cloud_task(run_id, ticker_up)
        if not enqueued:
            logger.warning(
                "Cloud Tasks enqueue unavailable — falling back to BackgroundTasks"
            )
            background_tasks.add_task(_sync_run, run_id, ticker_up)

    return RefreshResponse(run_id=run_id, ticker=ticker_up, status="queued")


def _enqueue_cloud_task(run_id: str, ticker: str) -> bool:
    """Submit a Cloud Tasks message that runs the insight-pipeline
    Cloud Run job with INSIGHT_RUN_ID / INSIGHT_TICKER env overrides.

    Returns True on successful enqueue, False on any failure (so the
    caller can fall back to BackgroundTasks).
    """
    try:
        from google.cloud import tasks_v2  # type: ignore
    except ImportError:
        return False

    project = os.environ.get("GCP_PROJECT_ID", "adept-mountain-474619-d4")
    region = os.environ.get("GCP_REGION", "us-east1")
    queue = os.environ.get("INSIGHT_TASKS_QUEUE", "insight-pipeline-queue")
    sa_email = os.environ.get(
        "INSIGHT_TASKS_SERVICE_ACCOUNT",
        f"trading-runner@{project}.iam.gserviceaccount.com",
    )
    job_url = (
        f"https://{region}-run.googleapis.com/apis/run.googleapis.com/v1/"
        f"namespaces/{project}/jobs/insight-pipeline:run"
    )

    try:
        client = tasks_v2.CloudTasksClient()
        parent = client.queue_path(project, region, queue)
        body = json.dumps(
            {
                "overrides": {
                    "containerOverrides": [
                        {
                            "env": [
                                {"name": "INSIGHT_RUN_ID", "value": run_id},
                                {"name": "INSIGHT_TICKER", "value": ticker},
                            ]
                        }
                    ]
                }
            }
        ).encode()
        task = {
            "http_request": {
                "http_method": tasks_v2.HttpMethod.POST,
                "url": job_url,
                "headers": {"Content-Type": "application/json"},
                "body": body,
                "oauth_token": {"service_account_email": sa_email},
            }
        }
        client.create_task(parent=parent, task=task)
        return True
    except Exception as exc:  # network, auth, queue-missing, etc.
        logger.warning("Cloud Tasks enqueue failed: %s", exc)
        return False


def _sync_run(run_id: str, ticker: str) -> None:
    """Synchronous wrapper around the async pipeline for BackgroundTasks."""
    try:
        asyncio.run(_execute_pipeline(run_id, ticker))
    except Exception:
        logger.exception("background run %s failed", run_id)


@router.get("/api/insights/runs/{run_id}", response_model=RunStatus)
async def get_run_status(run_id: str):
    """Poll the status of a refresh run."""
    try:
        UUID(run_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="run_id must be a UUID")
    row = _fetch_run(run_id)
    if row is None:
        raise HTTPException(status_code=404, detail=f"run {run_id} not found")
    return RunStatus(**row)


# ---------------------------------------------------------------------------
# Gemini Chat endpoint (restored from pre-agent-pipeline implementation)
# ---------------------------------------------------------------------------

CHAT_SYSTEM_PROMPTS = {
    "chat": (
        "You are a senior quantitative trader and portfolio manager with 20 years of "
        "institutional experience across equities, options, and systematic strategies. "
        "You are mentoring a developing trader who uses IWM/SPY/QQQ as their primary instruments.\n\n"
        "Available context you can reference:\n"
        "- Historical signals (330K+ entries with RSI, EMA, StochRSI, ATR, VWAP indicators)\n"
        "- Backtest results for systematic strategies on IWM/SPY/QQQ\n"
        "- Options GEX/VEX flow data (dealer positioning, king nodes, gatekeepers)\n"
        "- Playbook decision cards for each ticker\n\n"
        "Respond conversationally but tie advice back to actual data when possible. "
        "Be direct, specific, and constructive. Challenge assumptions. Don't give generic advice."
    ),
    "market": (
        "You are a derivatives market maker explaining current market structure to a trader on "
        "your desk. Be precise about levels, flows, and what matters today. Reference GEX/VEX "
        "data and explain dealer positioning. Focus on actionable insights for intraday trading."
    ),
    "strategy": (
        "You are a quantitative portfolio manager evaluating a retail trader's systematic strategy. "
        "Analyze it as if considering an allocation decision. Be rigorous and critical. Highlight "
        "risks, edge cases, and improvement opportunities. Reference specific metrics from their "
        "backtest data (win rate, profit factor, max drawdown, Sharpe)."
    ),
    "trade": (
        "You are a senior prop desk trader reviewing a junior trader's work. Be direct, specific, "
        "and constructive. Reference the actual numbers. Grade trades A-F with specific reasoning. "
        "Focus on: entry timing quality, exit optimization, setup alignment with playbook, "
        "and risk management."
    ),
}


class ChatMessage(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    message: str
    mode: str = "chat"
    ticker: str = "IWM"
    history: list[ChatMessage] = []


def _get_gemini_client():
    """Create a google-genai client for the chat endpoint."""
    from google import genai

    project = os.environ.get("GCP_PROJECT_ID", "adept-mountain-474619-d4")
    location = os.environ.get("GCP_REGION", "us-east1")
    key_file = os.environ.get(
        "GOOGLE_APPLICATION_CREDENTIALS",
        str(PROJECT_ROOT / ".gcp-key.json"),
    )

    credentials = None
    if key_file and Path(key_file).exists():
        from google.oauth2 import service_account

        credentials = service_account.Credentials.from_service_account_file(
            key_file,
            scopes=["https://www.googleapis.com/auth/cloud-platform"],
        )

    return genai.Client(
        vertexai=True,
        project=project,
        location=location,
        credentials=credentials,
    )


async def _stream_gemini(request: ChatRequest) -> AsyncGenerator[str, None]:
    """Stream response from Vertex AI Gemini."""
    try:
        from google.genai import types

        client = _get_gemini_client()

        contents: list[types.Content] = []
        for msg in request.history[-6:]:
            role = "user" if msg.role == "user" else "model"
            contents.append(types.Content(role=role, parts=[types.Part(text=msg.content)]))

        ticker_context = f"[Ticker: {request.ticker} | Mode: {request.mode}]\n\n"
        contents.append(
            types.Content(role="user", parts=[types.Part(text=ticker_context + request.message)])
        )

        system_prompt = CHAT_SYSTEM_PROMPTS.get(request.mode, CHAT_SYSTEM_PROMPTS["chat"])

        for chunk in client.models.generate_content_stream(
            model="gemini-2.0-flash",
            contents=contents,
            config=types.GenerateContentConfig(
                system_instruction=system_prompt,
                temperature=0.7,
                max_output_tokens=2048,
            ),
        ):
            if chunk.text:
                yield chunk.text

    except ImportError:
        yield (
            "google-genai SDK not installed.\n"
            "Run: pip install google-genai google-cloud-aiplatform"
        )
    except Exception as e:
        yield f"Gemini error: {e}"


@router.post("/api/insights/chat")
async def insights_chat(request: ChatRequest):
    """Stream a Gemini response for the given mode and message."""
    if not request.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty")
    if request.mode not in CHAT_SYSTEM_PROMPTS:
        raise HTTPException(status_code=400, detail=f"Unknown mode: {request.mode}")

    return StreamingResponse(
        _stream_gemini(request),
        media_type="text/plain",
        headers={"X-Content-Type-Options": "nosniff"},
    )
