"""
AI Insights router — structured multi-agent report endpoints.

Replaces the old Gemini chat endpoint. The report is generated by
the agent pipeline in lib.agents.orchestrator and persisted to
Cloud SQL's insight_reports table. The refresh endpoint enqueues a
run; clients poll /runs/{run_id} until status='done'.

In production, refresh dispatches a Cloud Tasks message to the
Cloud Run job (gcp/insight_pipeline_job.py). In local dev, it falls
back to FastAPI BackgroundTasks so you can exercise the full path
without spinning up infrastructure.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
from uuid import UUID, uuid4

from fastapi import APIRouter, BackgroundTasks, HTTPException, Path as PathParam
from pydantic import BaseModel

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from lib.agents.model_routing import _connect, load_routes_snapshot  # noqa: E402
from lib.agents.orchestrator import run_insight_pipeline  # noqa: E402
from lib.agents.schema import InsightReport  # noqa: E402
import lib.agents.vertex_adapter  # noqa: F401, E402 — registers adapter

router = APIRouter()
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------


class RunStatus(BaseModel):
    id: str
    ticker: str
    status: str
    trigger: str
    started_at: Optional[str] = None
    finished_at: Optional[str] = None
    error: Optional[str] = None
    report_id: Optional[str] = None


class RefreshResponse(BaseModel):
    run_id: str
    ticker: str
    status: str = "queued"


class ReportEnvelope(BaseModel):
    """Payload for GET /api/insights/report/{ticker}."""

    ticker: str
    as_of: str
    report: dict
    model_versions: dict
    cost_usd: Optional[float] = None
    latency_ms: Optional[int] = None


# ---------------------------------------------------------------------------
# DB helpers (raw SQL via the existing model_routing connection)
# ---------------------------------------------------------------------------


def _fetch_latest_report(ticker: str) -> Optional[dict]:
    conn = _connect()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT id::text, ticker, as_of, report, model_versions,
                       cost_usd, latency_ms
                FROM insight_reports
                WHERE ticker = %s
                ORDER BY as_of DESC
                LIMIT 1
                """,
                (ticker.upper(),),
            )
            row = cur.fetchone()
    finally:
        conn.close()
    if not row:
        return None
    return {
        "id": row[0],
        "ticker": row[1],
        "as_of": row[2].isoformat() if row[2] else None,
        "report": row[3],
        "model_versions": row[4],
        "cost_usd": float(row[5]) if row[5] is not None else None,
        "latency_ms": row[6],
    }


def _fetch_report_history(ticker: str, limit: int) -> list[dict]:
    conn = _connect()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT id::text, as_of,
                       report->>'direction' AS direction,
                       report->>'conviction' AS conviction,
                       report->>'thesis' AS thesis,
                       cost_usd
                FROM insight_reports
                WHERE ticker = %s
                ORDER BY as_of DESC
                LIMIT %s
                """,
                (ticker.upper(), limit),
            )
            rows = cur.fetchall()
    finally:
        conn.close()
    return [
        {
            "id": r[0],
            "as_of": r[1].isoformat() if r[1] else None,
            "direction": r[2],
            "conviction": r[3],
            "thesis": r[4],
            "cost_usd": float(r[5]) if r[5] is not None else None,
        }
        for r in rows
    ]


def _insert_run(ticker: str, trigger: str) -> str:
    conn = _connect()
    run_id = str(uuid4())
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO insight_runs (id, ticker, status, trigger)
                VALUES (%s, %s, 'queued', %s)
                """,
                (run_id, ticker.upper(), trigger),
            )
        conn.commit()
    finally:
        conn.close()
    return run_id


def _fetch_run(run_id: str) -> Optional[dict]:
    conn = _connect()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT id::text, ticker, status, trigger, started_at,
                       finished_at, error, report_id::text
                FROM insight_runs
                WHERE id = %s
                """,
                (run_id,),
            )
            row = cur.fetchone()
    finally:
        conn.close()
    if not row:
        return None
    return {
        "id": row[0],
        "ticker": row[1],
        "status": row[2],
        "trigger": row[3],
        "started_at": row[4].isoformat() if row[4] else None,
        "finished_at": row[5].isoformat() if row[5] else None,
        "error": row[6],
        "report_id": row[7],
    }


def _update_run_status(
    run_id: str,
    status: str,
    *,
    error: Optional[str] = None,
    report_id: Optional[str] = None,
) -> None:
    conn = _connect()
    try:
        with conn.cursor() as cur:
            if status == "running":
                cur.execute(
                    "UPDATE insight_runs SET status='running', started_at=NOW() WHERE id=%s",
                    (run_id,),
                )
            elif status == "done":
                cur.execute(
                    """
                    UPDATE insight_runs
                    SET status='done', finished_at=NOW(), report_id=%s
                    WHERE id=%s
                    """,
                    (report_id, run_id),
                )
            elif status == "failed":
                cur.execute(
                    """
                    UPDATE insight_runs
                    SET status='failed', finished_at=NOW(), error=%s
                    WHERE id=%s
                    """,
                    (error, run_id),
                )
        conn.commit()
    finally:
        conn.close()


def _upsert_report(report: InsightReport) -> str:
    """Upsert the report and return its row id."""
    conn = _connect()
    row_id = str(uuid4())
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO insight_reports
                    (id, ticker, as_of, report, model_versions, cost_usd, latency_ms)
                VALUES (%s, %s, %s, %s::jsonb, %s::jsonb, %s, %s)
                ON CONFLICT (ticker, as_of) DO UPDATE
                SET report = EXCLUDED.report,
                    model_versions = EXCLUDED.model_versions,
                    cost_usd = EXCLUDED.cost_usd,
                    latency_ms = EXCLUDED.latency_ms
                RETURNING id::text
                """,
                (
                    row_id,
                    report.ticker,
                    report.as_of,
                    report.model_dump_json(),
                    json.dumps(report.model_versions),
                    report.run_cost_usd,
                    report.run_latency_ms,
                ),
            )
            returned = cur.fetchone()
            if returned:
                row_id = returned[0]
        conn.commit()
    finally:
        conn.close()
    return row_id


# ---------------------------------------------------------------------------
# Background pipeline execution (local-dev only)
# ---------------------------------------------------------------------------


async def _execute_pipeline(run_id: str, ticker: str) -> None:
    """Run the pipeline and persist the result + run-status transitions."""
    _update_run_status(run_id, "running")
    try:
        snapshot = load_routes_snapshot()
        report = await run_insight_pipeline(ticker, snapshot=snapshot)
        report_id = _upsert_report(report)
        _update_run_status(run_id, "done", report_id=report_id)
    except Exception as exc:
        logger.exception("pipeline run %s failed", run_id)
        _update_run_status(run_id, "failed", error=str(exc))


def _is_local_dev() -> bool:
    return os.environ.get("ENV", "local").lower() in ("local", "dev", "development")


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.get("/api/insights/report/{ticker}", response_model=ReportEnvelope)
async def get_insight_report(ticker: str):
    """Return the most recent InsightReport for the ticker."""
    row = _fetch_latest_report(ticker)
    if row is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"No insight report for {ticker.upper()}. "
                "Call POST /api/insights/report/{ticker}/refresh to generate one."
            ),
        )
    return ReportEnvelope(
        ticker=row["ticker"],
        as_of=row["as_of"],
        report=row["report"],
        model_versions=row["model_versions"],
        cost_usd=row["cost_usd"],
        latency_ms=row["latency_ms"],
    )


@router.get("/api/insights/report/{ticker}/history")
async def get_insight_history(ticker: str, limit: int = 20):
    """Return a scannable list of recent reports for the ticker."""
    if limit < 1 or limit > 100:
        raise HTTPException(status_code=400, detail="limit must be between 1 and 100")
    rows = _fetch_report_history(ticker, limit)
    return {"ticker": ticker.upper(), "count": len(rows), "reports": rows}


@router.post(
    "/api/insights/report/{ticker}/refresh",
    response_model=RefreshResponse,
)
async def refresh_insight_report(
    ticker: str,
    background_tasks: BackgroundTasks,
):
    """Enqueue a fresh pipeline run for the ticker.

    Local dev: runs via FastAPI BackgroundTasks (survives within the
    process but not across restarts — acceptable for dev only).
    Production: will enqueue a Cloud Tasks message targeting the
    insight-pipeline Cloud Run job (see gcp/deploy.sh). The job
    transitions insight_runs.status as it executes.
    """
    ticker_up = ticker.upper()
    run_id = _insert_run(ticker_up, trigger="local_dev" if _is_local_dev() else "on_demand")

    if _is_local_dev():
        background_tasks.add_task(_sync_run, run_id, ticker_up)
    else:
        # Production Cloud Tasks enqueue is wired in segment 8.
        # For now, fall through to BackgroundTasks so the endpoint is
        # functional — the segment-8 commit will replace this branch.
        background_tasks.add_task(_sync_run, run_id, ticker_up)

    return RefreshResponse(run_id=run_id, ticker=ticker_up, status="queued")


def _sync_run(run_id: str, ticker: str) -> None:
    """Synchronous wrapper around the async pipeline for BackgroundTasks."""
    try:
        asyncio.run(_execute_pipeline(run_id, ticker))
    except Exception:
        logger.exception("background run %s failed", run_id)


@router.get("/api/insights/runs/{run_id}", response_model=RunStatus)
async def get_run_status(run_id: str):
    """Poll the status of a refresh run."""
    try:
        UUID(run_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="run_id must be a UUID")
    row = _fetch_run(run_id)
    if row is None:
        raise HTTPException(status_code=404, detail=f"run {run_id} not found")
    return RunStatus(**row)
